package com.nexts.gs.enums;

public enum ElementTypeEnum {
  TIGER_CLINK, TIGER_SOJU_CAN, TIGER_PLATINUM_CAN, COIN, LOGO_TIGER, FIRE_WORK,
  HEINEKEN_CLINK, HEINEKEN_SLIVER_CAN, HEINEKEN_00_CAN, LOGO_HEINEKEN
}
